### ISSUE TITLE
Fix routing / base of React app at GitHub Pages

### ISSUE THREAD

**Issue by hugovk** [digiaonline/react-foundation-docs#29]
This React app is deployed to https://digia.online/react-foundation-docs/

But there's a 404 loading the app:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Foundation as React components">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>React + Foundation · Foundation as React components</title>
</head>
<body>
<div id="root"></div>
<script type="text/javascript" src="/app.7b5695e2abaf01cd6a5b.js"></script></body>
</html>
```

That's because it's trying to load the app at 

* https://digia.online/app.7b5695e2abaf01cd6a5b.js

When it's really at:

* https://digia.online/react-foundation-docs/app.7b5695e2abaf01cd6a5b.js

It needs fixing so everything loads properly.

**Comment by raulsoledispa** [comment]
Hi, I would like to can help you. Can you assign me it?

**Comment by supanthapaul** [comment]
I've fixed the issue, please review the PR.
#31
