### ISSUE TITLE
Document new components

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/react-foundation-docs#6]
* [ ] Accordion
* [ ] Tabs
* [ ] Reveal

**Comment by hugovk** [comment]
GitHub tip: this markdown makes clickable TODO items:
```
* [ ] Unchecked TODO
* [x] Checked TODO
```
Produces:
* [ ] Unchecked TODO
* [x] Checked TODO

**Comment by Jalle19** [comment]
Thanks, updated

**Comment by kbrabrand** [comment]
#7
